// GLBasicLib_gl.h
// Copyright (C) Thomas Mulgrew (tmulgrew@slingshot.co.nz)// Generated by GLBasic header scanner
// From C:\Program Files\Borland\CBuilder6\Include\Gl\gl.h

#ifndef _GLBasicLib_gl_h
#define _GLBasicLib_gl_h
#include "TomComp.h"

// Registration function
void InitGLBasicLib_gl(TomBasicCompiler& comp);
#endif
